"""Add Fleet API support

Revision ID: 5fa2bffb0341
Revises: 37d78bc60237
Create Date: 2025-11-24 16:05:35.128909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa2bffb0341'
down_revision = '37d78bc60237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesla_api_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fleet_api_access_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('fleet_api_refresh_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('fleet_api_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fleet_api_token_expires_at')
        batch_op.drop_column('fleet_api_refresh_token_encrypted')
        batch_op.drop_column('fleet_api_access_token_encrypted')
        batch_op.drop_column('tesla_api_provider')

    # ### end Alembic commands ###
