"""Add Cloudflare tunnel configuration

Revision ID: 60416c1edc02
Revises: e510af51951e
Create Date: 2025-12-12 20:54:17.384904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60416c1edc02'
down_revision = 'e510af51951e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudflare_tunnel_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_tunnel_domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_tunnel_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cloudflare_tunnel_enabled')
        batch_op.drop_column('cloudflare_tunnel_domain')
        batch_op.drop_column('cloudflare_tunnel_token_encrypted')

    # ### end Alembic commands ###
