"""Add demand_artificial_price_enabled field

Revision ID: 6f59916b99d5
Revises: 1bc1a0544dad
Create Date: 2025-12-09 17:27:04.797189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f59916b99d5'
down_revision = '1bc1a0544dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demand_artificial_price_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('demand_artificial_price_enabled')

    # ### end Alembic commands ###
