"""Add Fleet API client credentials to User model

Revision ID: a54dbb75f762
Revises: 5fa2bffb0341
Create Date: 2025-11-24 16:54:48.419378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54dbb75f762'
down_revision = '5fa2bffb0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fleet_api_client_id_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('fleet_api_client_secret_encrypted', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fleet_api_client_secret_encrypted')
        batch_op.drop_column('fleet_api_client_id_encrypted')

    # ### end Alembic commands ###
