"""Shared LP/greedy solver constants."""

from __future__ import annotations

BELOW_RESERVE_RECOVERY_HOLD_MARGIN_SOC = 0.02
PRE_WINDOW_REACHABLE_TARGET_MARGIN_SOC = 0.005
PRE_WINDOW_REACHABILITY_MARGIN_SOC = 1e-6
MODE_PROJECTION_MAX_ITERATIONS = 8

ACTION_THRESHOLD_W = 100.0
DEFAULT_IMPORT_PRICE = 0.30
DEFAULT_EXPORT_PRICE = 0.08
DEFAULT_EFFICIENCY = 0.92

LP_SOLVER_TIME_LIMIT_SECONDS = 30.0
LP_NEAR_HORIZON_HOURS = 6
LP_MID_HORIZON_HOURS = 24
LP_MID_PERIOD_MINUTES = 30
LP_FAR_PERIOD_MINUTES = 60
LP_PRICE_SPLIT_THRESHOLD = 0.02
LP_POWER_SPLIT_THRESHOLD_KW = ACTION_THRESHOLD_W / 1000.0

PRE_WINDOW_SOLAR_CREDIT_FACTOR = 0.80
PRE_WINDOW_SOLAR_BUFFER_SOC = 0.03
