name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
          # HACS relies on GitHub license detection, which does not currently
          # identify PolyForm Noncommercial as an SPDX license.
          ignore: license
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
